title: Yang Xie
description: This dude is a 5th-year Ph.D. student in the Electrical and Computer Engineering department of the University of Maryland, College Park. His advisor is Prof. Ankur Srivastava. His current research focuses on electronic design automation and hardware security. He is also passionate about machine learning applications and data modeling.
show_downloads: false
google_analytics: UA-35823732-1
theme: jekyll-theme-minimal
