title: Yang Xie
description: I'm joining Facebook as a Research Scientist. Before that, I was a Grad Terp in the Electrical and Computer Engineering department of the University of Maryland, College Park. My advisor is Prof. Ankur Srivastava.
show_downloads: false
google_analytics: UA-35823732-1
theme: jekyll-theme-minimal
